#pragma once
#include "stdlib/graphics/resource.hpp"
#include <cstdint>
namespace tx_generated
{
struct record_type;
}
extern "C"
{
int txrt_gui_id_progress_bar(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_is_open_progress_bar(tx_generated::graphics::resource* control, bool* result) noexcept;
int txrt_gui_close_progress_bar(tx_generated::graphics::resource* control) noexcept;
int txrt_gui_set_enabled_progress_bar(tx_generated::graphics::resource* control, bool enabled) noexcept;
int txrt_gui_set_visible_progress_bar(tx_generated::graphics::resource* control, bool visible) noexcept;
int txrt_gui_set_reserved_space_progress_bar(tx_generated::graphics::resource* control, bool reserved) noexcept;
int txrt_gui_set_width_progress_bar(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_height_progress_bar(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_constraints_progress_bar(tx_generated::graphics::resource* control, double min_width, double min_height, double max_width, double max_height) noexcept;
int txrt_gui_set_margin_progress_bar(tx_generated::graphics::resource* control, double margin) noexcept;
int txrt_gui_set_alignment_progress_bar(tx_generated::graphics::resource* control, const void* horizontal, const void* vertical) noexcept;
int txrt_gui_set_cell_progress_bar(tx_generated::graphics::resource* control, std::int64_t row, std::int64_t column, std::int64_t row_span, std::int64_t column_span) noexcept;
int txrt_gui_id_slider(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_is_open_slider(tx_generated::graphics::resource* control, bool* result) noexcept;
int txrt_gui_close_slider(tx_generated::graphics::resource* control) noexcept;
int txrt_gui_set_enabled_slider(tx_generated::graphics::resource* control, bool enabled) noexcept;
int txrt_gui_set_visible_slider(tx_generated::graphics::resource* control, bool visible) noexcept;
int txrt_gui_set_reserved_space_slider(tx_generated::graphics::resource* control, bool reserved) noexcept;
int txrt_gui_set_width_slider(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_height_slider(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_constraints_slider(tx_generated::graphics::resource* control, double min_width, double min_height, double max_width, double max_height) noexcept;
int txrt_gui_set_margin_slider(tx_generated::graphics::resource* control, double margin) noexcept;
int txrt_gui_set_alignment_slider(tx_generated::graphics::resource* control, const void* horizontal, const void* vertical) noexcept;
int txrt_gui_set_cell_slider(tx_generated::graphics::resource* control, std::int64_t row, std::int64_t column, std::int64_t row_span, std::int64_t column_span) noexcept;
int txrt_gui_id_tabs(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_is_open_tabs(tx_generated::graphics::resource* control, bool* result) noexcept;
int txrt_gui_close_tabs(tx_generated::graphics::resource* control) noexcept;
int txrt_gui_set_enabled_tabs(tx_generated::graphics::resource* control, bool enabled) noexcept;
int txrt_gui_set_visible_tabs(tx_generated::graphics::resource* control, bool visible) noexcept;
int txrt_gui_set_reserved_space_tabs(tx_generated::graphics::resource* control, bool reserved) noexcept;
int txrt_gui_set_width_tabs(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_height_tabs(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_constraints_tabs(tx_generated::graphics::resource* control, double min_width, double min_height, double max_width, double max_height) noexcept;
int txrt_gui_set_margin_tabs(tx_generated::graphics::resource* control, double margin) noexcept;
int txrt_gui_set_alignment_tabs(tx_generated::graphics::resource* control, const void* horizontal, const void* vertical) noexcept;
int txrt_gui_set_cell_tabs(tx_generated::graphics::resource* control, std::int64_t row, std::int64_t column, std::int64_t row_span, std::int64_t column_span) noexcept;
int txrt_gui_id_canvas(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_is_open_canvas(tx_generated::graphics::resource* control, bool* result) noexcept;
int txrt_gui_close_canvas(tx_generated::graphics::resource* control) noexcept;
int txrt_gui_set_enabled_canvas(tx_generated::graphics::resource* control, bool enabled) noexcept;
int txrt_gui_set_visible_canvas(tx_generated::graphics::resource* control, bool visible) noexcept;
int txrt_gui_set_reserved_space_canvas(tx_generated::graphics::resource* control, bool reserved) noexcept;
int txrt_gui_set_width_canvas(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_height_canvas(tx_generated::graphics::resource* control, const void* value_mode, double value_value) noexcept;
int txrt_gui_set_constraints_canvas(tx_generated::graphics::resource* control, double min_width, double min_height, double max_width, double max_height) noexcept;
int txrt_gui_set_margin_canvas(tx_generated::graphics::resource* control, double margin) noexcept;
int txrt_gui_set_alignment_canvas(tx_generated::graphics::resource* control, const void* horizontal, const void* vertical) noexcept;
int txrt_gui_set_cell_canvas(tx_generated::graphics::resource* control, std::int64_t row, std::int64_t column, std::int64_t row_span, std::int64_t column_span) noexcept;
int txrt_gui_focus_container(tx_generated::graphics::resource* control, const char* type, void** result) noexcept;
int txrt_gui_focus_slider(tx_generated::graphics::resource* control, const char* type, void** result) noexcept;
int txrt_gui_focus_tabs(tx_generated::graphics::resource* control, const char* type, void** result) noexcept;
int txrt_gui_focus_canvas(tx_generated::graphics::resource* control, const char* type, void** result) noexcept;
int txrt_gui_set_accessibility_container(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_container(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_label(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_label(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_button(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_button(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_text_box(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_text_box(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_check_box(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_check_box(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_list_view(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_list_view(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_table_view(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_table_view(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_tree_view(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_tree_view(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_progress_bar(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_progress_bar(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_slider(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_slider(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_tabs(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_tabs(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_set_accessibility_canvas(tx_generated::graphics::resource* control, const void* name, const void* help) noexcept;
int txrt_gui_set_label_canvas(tx_generated::graphics::resource* control, tx_generated::graphics::resource* label) noexcept;
int txrt_gui_create_tabs(tx_generated::graphics::resource* parent, const char* type, void** result) noexcept;
int txrt_gui_add_tab(tx_generated::graphics::resource* tabs, const void* title, const char* type, void** result) noexcept;
int txrt_gui_select_tab(tx_generated::graphics::resource* tabs, tx_generated::graphics::resource* page) noexcept;
int txrt_gui_selected_tab(tx_generated::graphics::resource* tabs, const char* type, void** result) noexcept;
int txrt_gui_create_scroll(tx_generated::graphics::resource* parent, bool horizontal, bool vertical, const char* type, void** result) noexcept;
int txrt_gui_set_scroll_position(tx_generated::graphics::resource* control, double x, double y) noexcept;
int txrt_gui_scroll_x(tx_generated::graphics::resource* control, double* result) noexcept;
int txrt_gui_scroll_y(tx_generated::graphics::resource* control, double* result) noexcept;
int txrt_gui_create_split(tx_generated::graphics::resource* parent, bool vertical, double position, double minimum_first, double minimum_second, const char* type, void** result) noexcept;
int txrt_gui_split_pane(tx_generated::graphics::resource* control, std::int64_t index, const char* type, void** result) noexcept;
int txrt_gui_set_split_position(tx_generated::graphics::resource* control, double position) noexcept;
int txrt_gui_split_position(tx_generated::graphics::resource* control, double* result) noexcept;
int txrt_gui_create_progress_bar(tx_generated::graphics::resource* parent, const char* type, void** result) noexcept;
int txrt_gui_set_progress(tx_generated::graphics::resource* control, std::int64_t minimum, std::int64_t maximum, std::int64_t value) noexcept;
int txrt_gui_progress_value(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_set_indeterminate(tx_generated::graphics::resource* control, bool enabled) noexcept;
int txrt_gui_create_slider(tx_generated::graphics::resource* parent, std::int64_t minimum, std::int64_t maximum, std::int64_t value, std::int64_t step, const char* type, void** result) noexcept;
int txrt_gui_set_slider_value(tx_generated::graphics::resource* control, std::int64_t value) noexcept;
int txrt_gui_slider_value(tx_generated::graphics::resource* control, std::int64_t* result) noexcept;
int txrt_gui_create_canvas(tx_generated::graphics::resource* parent, const char* type, void** result) noexcept;
int txrt_gui_begin_canvas(tx_generated::graphics::resource* control, const char* type, void** result) noexcept;
int txrt_gui_invalidate_canvas(tx_generated::graphics::resource* control) noexcept;
int txrt_gui_canvas_width(tx_generated::graphics::resource* control, double* result) noexcept;
int txrt_gui_canvas_height(tx_generated::graphics::resource* control, double* result) noexcept;
int txrt_gui_high_contrast(bool* result) noexcept;
int txrt_gui_theme_color(const void* role, const tx_generated::record_type* type, void** result) noexcept;
}
