#pragma once

#include <cstdint>

extern "C"
{

int txrt_map_new_i64_i64(void** result) noexcept;
int txrt_map_size_i64_i64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_i64_i64(const void* value, bool* result) noexcept;
int txrt_map_clear_i64_i64(const void* value) noexcept;
int txrt_map_contains_i64_i64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_remove_i64_i64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_set_i64_i64(const void* value, std::int64_t key, std::int64_t item) noexcept;
int txrt_map_read_i64_i64(const void* value, std::int64_t key, std::int64_t* result) noexcept;
int txrt_map_get_i64_i64(const void* value, std::int64_t key, std::int64_t fallback, std::int64_t* result) noexcept;
int txrt_map_keys_i64_i64(const void* value, void** result) noexcept;
int txrt_map_values_i64_i64(const void* value, void** result) noexcept;
int txrt_map_new_i64_f64(void** result) noexcept;
int txrt_map_size_i64_f64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_i64_f64(const void* value, bool* result) noexcept;
int txrt_map_clear_i64_f64(const void* value) noexcept;
int txrt_map_contains_i64_f64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_remove_i64_f64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_set_i64_f64(const void* value, std::int64_t key, double item) noexcept;
int txrt_map_read_i64_f64(const void* value, std::int64_t key, double* result) noexcept;
int txrt_map_get_i64_f64(const void* value, std::int64_t key, double fallback, double* result) noexcept;
int txrt_map_keys_i64_f64(const void* value, void** result) noexcept;
int txrt_map_values_i64_f64(const void* value, void** result) noexcept;
int txrt_map_new_i64_bool(void** result) noexcept;
int txrt_map_size_i64_bool(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_i64_bool(const void* value, bool* result) noexcept;
int txrt_map_clear_i64_bool(const void* value) noexcept;
int txrt_map_contains_i64_bool(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_remove_i64_bool(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_set_i64_bool(const void* value, std::int64_t key, bool item) noexcept;
int txrt_map_read_i64_bool(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_get_i64_bool(const void* value, std::int64_t key, bool fallback, bool* result) noexcept;
int txrt_map_keys_i64_bool(const void* value, void** result) noexcept;
int txrt_map_values_i64_bool(const void* value, void** result) noexcept;
int txrt_map_new_i64_str(void** result) noexcept;
int txrt_map_size_i64_str(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_i64_str(const void* value, bool* result) noexcept;
int txrt_map_clear_i64_str(const void* value) noexcept;
int txrt_map_contains_i64_str(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_remove_i64_str(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_map_set_i64_str(const void* value, std::int64_t key, const void* item) noexcept;
int txrt_map_read_i64_str(const void* value, std::int64_t key, void** result) noexcept;
int txrt_map_get_i64_str(const void* value, std::int64_t key, const void* fallback, void** result) noexcept;
int txrt_map_keys_i64_str(const void* value, void** result) noexcept;
int txrt_map_values_i64_str(const void* value, void** result) noexcept;
int txrt_map_new_f64_i64(void** result) noexcept;
int txrt_map_size_f64_i64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_f64_i64(const void* value, bool* result) noexcept;
int txrt_map_clear_f64_i64(const void* value) noexcept;
int txrt_map_contains_f64_i64(const void* value, double key, bool* result) noexcept;
int txrt_map_remove_f64_i64(const void* value, double key, bool* result) noexcept;
int txrt_map_set_f64_i64(const void* value, double key, std::int64_t item) noexcept;
int txrt_map_read_f64_i64(const void* value, double key, std::int64_t* result) noexcept;
int txrt_map_get_f64_i64(const void* value, double key, std::int64_t fallback, std::int64_t* result) noexcept;
int txrt_map_keys_f64_i64(const void* value, void** result) noexcept;
int txrt_map_values_f64_i64(const void* value, void** result) noexcept;
int txrt_map_new_f64_f64(void** result) noexcept;
int txrt_map_size_f64_f64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_f64_f64(const void* value, bool* result) noexcept;
int txrt_map_clear_f64_f64(const void* value) noexcept;
int txrt_map_contains_f64_f64(const void* value, double key, bool* result) noexcept;
int txrt_map_remove_f64_f64(const void* value, double key, bool* result) noexcept;
int txrt_map_set_f64_f64(const void* value, double key, double item) noexcept;
int txrt_map_read_f64_f64(const void* value, double key, double* result) noexcept;
int txrt_map_get_f64_f64(const void* value, double key, double fallback, double* result) noexcept;
int txrt_map_keys_f64_f64(const void* value, void** result) noexcept;
int txrt_map_values_f64_f64(const void* value, void** result) noexcept;
int txrt_map_new_f64_bool(void** result) noexcept;
int txrt_map_size_f64_bool(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_f64_bool(const void* value, bool* result) noexcept;
int txrt_map_clear_f64_bool(const void* value) noexcept;
int txrt_map_contains_f64_bool(const void* value, double key, bool* result) noexcept;
int txrt_map_remove_f64_bool(const void* value, double key, bool* result) noexcept;
int txrt_map_set_f64_bool(const void* value, double key, bool item) noexcept;
int txrt_map_read_f64_bool(const void* value, double key, bool* result) noexcept;
int txrt_map_get_f64_bool(const void* value, double key, bool fallback, bool* result) noexcept;
int txrt_map_keys_f64_bool(const void* value, void** result) noexcept;
int txrt_map_values_f64_bool(const void* value, void** result) noexcept;
int txrt_map_new_f64_str(void** result) noexcept;
int txrt_map_size_f64_str(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_f64_str(const void* value, bool* result) noexcept;
int txrt_map_clear_f64_str(const void* value) noexcept;
int txrt_map_contains_f64_str(const void* value, double key, bool* result) noexcept;
int txrt_map_remove_f64_str(const void* value, double key, bool* result) noexcept;
int txrt_map_set_f64_str(const void* value, double key, const void* item) noexcept;
int txrt_map_read_f64_str(const void* value, double key, void** result) noexcept;
int txrt_map_get_f64_str(const void* value, double key, const void* fallback, void** result) noexcept;
int txrt_map_keys_f64_str(const void* value, void** result) noexcept;
int txrt_map_values_f64_str(const void* value, void** result) noexcept;
int txrt_map_new_bool_i64(void** result) noexcept;
int txrt_map_size_bool_i64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_bool_i64(const void* value, bool* result) noexcept;
int txrt_map_clear_bool_i64(const void* value) noexcept;
int txrt_map_contains_bool_i64(const void* value, bool key, bool* result) noexcept;
int txrt_map_remove_bool_i64(const void* value, bool key, bool* result) noexcept;
int txrt_map_set_bool_i64(const void* value, bool key, std::int64_t item) noexcept;
int txrt_map_read_bool_i64(const void* value, bool key, std::int64_t* result) noexcept;
int txrt_map_get_bool_i64(const void* value, bool key, std::int64_t fallback, std::int64_t* result) noexcept;
int txrt_map_keys_bool_i64(const void* value, void** result) noexcept;
int txrt_map_values_bool_i64(const void* value, void** result) noexcept;
int txrt_map_new_bool_f64(void** result) noexcept;
int txrt_map_size_bool_f64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_bool_f64(const void* value, bool* result) noexcept;
int txrt_map_clear_bool_f64(const void* value) noexcept;
int txrt_map_contains_bool_f64(const void* value, bool key, bool* result) noexcept;
int txrt_map_remove_bool_f64(const void* value, bool key, bool* result) noexcept;
int txrt_map_set_bool_f64(const void* value, bool key, double item) noexcept;
int txrt_map_read_bool_f64(const void* value, bool key, double* result) noexcept;
int txrt_map_get_bool_f64(const void* value, bool key, double fallback, double* result) noexcept;
int txrt_map_keys_bool_f64(const void* value, void** result) noexcept;
int txrt_map_values_bool_f64(const void* value, void** result) noexcept;
int txrt_map_new_bool_bool(void** result) noexcept;
int txrt_map_size_bool_bool(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_bool_bool(const void* value, bool* result) noexcept;
int txrt_map_clear_bool_bool(const void* value) noexcept;
int txrt_map_contains_bool_bool(const void* value, bool key, bool* result) noexcept;
int txrt_map_remove_bool_bool(const void* value, bool key, bool* result) noexcept;
int txrt_map_set_bool_bool(const void* value, bool key, bool item) noexcept;
int txrt_map_read_bool_bool(const void* value, bool key, bool* result) noexcept;
int txrt_map_get_bool_bool(const void* value, bool key, bool fallback, bool* result) noexcept;
int txrt_map_keys_bool_bool(const void* value, void** result) noexcept;
int txrt_map_values_bool_bool(const void* value, void** result) noexcept;
int txrt_map_new_bool_str(void** result) noexcept;
int txrt_map_size_bool_str(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_bool_str(const void* value, bool* result) noexcept;
int txrt_map_clear_bool_str(const void* value) noexcept;
int txrt_map_contains_bool_str(const void* value, bool key, bool* result) noexcept;
int txrt_map_remove_bool_str(const void* value, bool key, bool* result) noexcept;
int txrt_map_set_bool_str(const void* value, bool key, const void* item) noexcept;
int txrt_map_read_bool_str(const void* value, bool key, void** result) noexcept;
int txrt_map_get_bool_str(const void* value, bool key, const void* fallback, void** result) noexcept;
int txrt_map_keys_bool_str(const void* value, void** result) noexcept;
int txrt_map_values_bool_str(const void* value, void** result) noexcept;
int txrt_map_new_str_i64(void** result) noexcept;
int txrt_map_size_str_i64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_str_i64(const void* value, bool* result) noexcept;
int txrt_map_clear_str_i64(const void* value) noexcept;
int txrt_map_contains_str_i64(const void* value, const void* key, bool* result) noexcept;
int txrt_map_remove_str_i64(const void* value, const void* key, bool* result) noexcept;
int txrt_map_set_str_i64(const void* value, const void* key, std::int64_t item) noexcept;
int txrt_map_read_str_i64(const void* value, const void* key, std::int64_t* result) noexcept;
int txrt_map_get_str_i64(const void* value, const void* key, std::int64_t fallback, std::int64_t* result) noexcept;
int txrt_map_keys_str_i64(const void* value, void** result) noexcept;
int txrt_map_values_str_i64(const void* value, void** result) noexcept;
int txrt_map_new_str_f64(void** result) noexcept;
int txrt_map_size_str_f64(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_str_f64(const void* value, bool* result) noexcept;
int txrt_map_clear_str_f64(const void* value) noexcept;
int txrt_map_contains_str_f64(const void* value, const void* key, bool* result) noexcept;
int txrt_map_remove_str_f64(const void* value, const void* key, bool* result) noexcept;
int txrt_map_set_str_f64(const void* value, const void* key, double item) noexcept;
int txrt_map_read_str_f64(const void* value, const void* key, double* result) noexcept;
int txrt_map_get_str_f64(const void* value, const void* key, double fallback, double* result) noexcept;
int txrt_map_keys_str_f64(const void* value, void** result) noexcept;
int txrt_map_values_str_f64(const void* value, void** result) noexcept;
int txrt_map_new_str_bool(void** result) noexcept;
int txrt_map_size_str_bool(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_str_bool(const void* value, bool* result) noexcept;
int txrt_map_clear_str_bool(const void* value) noexcept;
int txrt_map_contains_str_bool(const void* value, const void* key, bool* result) noexcept;
int txrt_map_remove_str_bool(const void* value, const void* key, bool* result) noexcept;
int txrt_map_set_str_bool(const void* value, const void* key, bool item) noexcept;
int txrt_map_read_str_bool(const void* value, const void* key, bool* result) noexcept;
int txrt_map_get_str_bool(const void* value, const void* key, bool fallback, bool* result) noexcept;
int txrt_map_keys_str_bool(const void* value, void** result) noexcept;
int txrt_map_values_str_bool(const void* value, void** result) noexcept;
int txrt_map_new_str_str(void** result) noexcept;
int txrt_map_size_str_str(const void* value, std::int64_t* result) noexcept;
int txrt_map_empty_str_str(const void* value, bool* result) noexcept;
int txrt_map_clear_str_str(const void* value) noexcept;
int txrt_map_contains_str_str(const void* value, const void* key, bool* result) noexcept;
int txrt_map_remove_str_str(const void* value, const void* key, bool* result) noexcept;
int txrt_map_set_str_str(const void* value, const void* key, const void* item) noexcept;
int txrt_map_read_str_str(const void* value, const void* key, void** result) noexcept;
int txrt_map_get_str_str(const void* value, const void* key, const void* fallback, void** result) noexcept;
int txrt_map_keys_str_str(const void* value, void** result) noexcept;
int txrt_map_values_str_str(const void* value, void** result) noexcept;
int txrt_set_new_i64(void** result) noexcept;
int txrt_set_size_i64(const void* value, std::int64_t* result) noexcept;
int txrt_set_empty_i64(const void* value, bool* result) noexcept;
int txrt_set_clear_i64(const void* value) noexcept;
int txrt_set_contains_i64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_set_remove_i64(const void* value, std::int64_t key, bool* result) noexcept;
int txrt_set_to_vector_i64(const void* value, void** result) noexcept;
int txrt_set_insert_i64(const void* value, std::int64_t item, bool* result) noexcept;
int txrt_set_new_f64(void** result) noexcept;
int txrt_set_size_f64(const void* value, std::int64_t* result) noexcept;
int txrt_set_empty_f64(const void* value, bool* result) noexcept;
int txrt_set_clear_f64(const void* value) noexcept;
int txrt_set_contains_f64(const void* value, double key, bool* result) noexcept;
int txrt_set_remove_f64(const void* value, double key, bool* result) noexcept;
int txrt_set_to_vector_f64(const void* value, void** result) noexcept;
int txrt_set_insert_f64(const void* value, double item, bool* result) noexcept;
int txrt_set_new_bool(void** result) noexcept;
int txrt_set_size_bool(const void* value, std::int64_t* result) noexcept;
int txrt_set_empty_bool(const void* value, bool* result) noexcept;
int txrt_set_clear_bool(const void* value) noexcept;
int txrt_set_contains_bool(const void* value, bool key, bool* result) noexcept;
int txrt_set_remove_bool(const void* value, bool key, bool* result) noexcept;
int txrt_set_to_vector_bool(const void* value, void** result) noexcept;
int txrt_set_insert_bool(const void* value, bool item, bool* result) noexcept;
int txrt_set_new_str(void** result) noexcept;
int txrt_set_size_str(const void* value, std::int64_t* result) noexcept;
int txrt_set_empty_str(const void* value, bool* result) noexcept;
int txrt_set_clear_str(const void* value) noexcept;
int txrt_set_contains_str(const void* value, const void* key, bool* result) noexcept;
int txrt_set_remove_str(const void* value, const void* key, bool* result) noexcept;
int txrt_set_to_vector_str(const void* value, void** result) noexcept;
int txrt_set_insert_str(const void* value, const void* item, bool* result) noexcept;
int txrt_heap_new_i64(bool descending, void** result) noexcept;
int txrt_heap_size_i64(const void* value, std::int64_t* result) noexcept;
int txrt_heap_empty_i64(const void* value, bool* result) noexcept;
int txrt_heap_clear_i64(const void* value) noexcept;
int txrt_heap_to_vector_i64(const void* value, void** result) noexcept;
int txrt_heap_push_i64(const void* value, std::int64_t item) noexcept;
int txrt_heap_pop_i64(const void* value) noexcept;
int txrt_heap_top_i64(const void* value, std::int64_t* result) noexcept;
int txrt_heap_new_f64(bool descending, void** result) noexcept;
int txrt_heap_size_f64(const void* value, std::int64_t* result) noexcept;
int txrt_heap_empty_f64(const void* value, bool* result) noexcept;
int txrt_heap_clear_f64(const void* value) noexcept;
int txrt_heap_to_vector_f64(const void* value, void** result) noexcept;
int txrt_heap_push_f64(const void* value, double item) noexcept;
int txrt_heap_pop_f64(const void* value) noexcept;
int txrt_heap_top_f64(const void* value, double* result) noexcept;
int txrt_heap_new_bool(bool descending, void** result) noexcept;
int txrt_heap_size_bool(const void* value, std::int64_t* result) noexcept;
int txrt_heap_empty_bool(const void* value, bool* result) noexcept;
int txrt_heap_clear_bool(const void* value) noexcept;
int txrt_heap_to_vector_bool(const void* value, void** result) noexcept;
int txrt_heap_push_bool(const void* value, bool item) noexcept;
int txrt_heap_pop_bool(const void* value) noexcept;
int txrt_heap_top_bool(const void* value, bool* result) noexcept;
int txrt_heap_new_str(bool descending, void** result) noexcept;
int txrt_heap_size_str(const void* value, std::int64_t* result) noexcept;
int txrt_heap_empty_str(const void* value, bool* result) noexcept;
int txrt_heap_clear_str(const void* value) noexcept;
int txrt_heap_to_vector_str(const void* value, void** result) noexcept;
int txrt_heap_push_str(const void* value, const void* item) noexcept;
int txrt_heap_pop_str(const void* value) noexcept;
int txrt_heap_top_str(const void* value, void** result) noexcept;
int txrt_queue_new_i64(void** result) noexcept;
int txrt_queue_size_i64(const void* value, std::int64_t* result) noexcept;
int txrt_queue_empty_i64(const void* value, bool* result) noexcept;
int txrt_queue_clear_i64(const void* value) noexcept;
int txrt_queue_to_vector_i64(const void* value, void** result) noexcept;
int txrt_queue_push_i64(const void* value, std::int64_t item) noexcept;
int txrt_queue_pop_i64(const void* value) noexcept;
int txrt_queue_front_i64(const void* value, std::int64_t* result) noexcept;
int txrt_queue_back_i64(const void* value, std::int64_t* result) noexcept;
int txrt_queue_new_f64(void** result) noexcept;
int txrt_queue_size_f64(const void* value, std::int64_t* result) noexcept;
int txrt_queue_empty_f64(const void* value, bool* result) noexcept;
int txrt_queue_clear_f64(const void* value) noexcept;
int txrt_queue_to_vector_f64(const void* value, void** result) noexcept;
int txrt_queue_push_f64(const void* value, double item) noexcept;
int txrt_queue_pop_f64(const void* value) noexcept;
int txrt_queue_front_f64(const void* value, double* result) noexcept;
int txrt_queue_back_f64(const void* value, double* result) noexcept;
int txrt_queue_new_bool(void** result) noexcept;
int txrt_queue_size_bool(const void* value, std::int64_t* result) noexcept;
int txrt_queue_empty_bool(const void* value, bool* result) noexcept;
int txrt_queue_clear_bool(const void* value) noexcept;
int txrt_queue_to_vector_bool(const void* value, void** result) noexcept;
int txrt_queue_push_bool(const void* value, bool item) noexcept;
int txrt_queue_pop_bool(const void* value) noexcept;
int txrt_queue_front_bool(const void* value, bool* result) noexcept;
int txrt_queue_back_bool(const void* value, bool* result) noexcept;
int txrt_queue_new_str(void** result) noexcept;
int txrt_queue_size_str(const void* value, std::int64_t* result) noexcept;
int txrt_queue_empty_str(const void* value, bool* result) noexcept;
int txrt_queue_clear_str(const void* value) noexcept;
int txrt_queue_to_vector_str(const void* value, void** result) noexcept;
int txrt_queue_push_str(const void* value, const void* item) noexcept;
int txrt_queue_pop_str(const void* value) noexcept;
int txrt_queue_front_str(const void* value, void** result) noexcept;
int txrt_queue_back_str(const void* value, void** result) noexcept;

}
