// Unicode 数据生成工具；算法实现不来自第三方库。
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';

const sources = [
    ['extracted/DerivedBidiClass.txt', '71ed943a49c58568d8d92e80ecc2ba2f06e62aee9c8ebb0e6e8bd2c3ed8b180e'],
    ['BidiBrackets.txt', 'b8f32554c6f658821fb0ee742d21c5b1f2086b9bf13071fed04894b022f93d67'],
    ['BidiMirroring.txt', 'd7afdadd1bbd66f5a663ac0e8f7958f18fd9491fc0bc59ec5877cb82db71db7d'],
    ['BidiTest.txt', '93e5eb9d88ca89dcf895f5576486a3363762ad2aa8f2db2fa56fe60cb82b9520'],
    ['BidiCharacterTest.txt', 'd04a51a90052dcd71c4e91ee5b3a9d973ee35c12406b5a99875ac8163c8f2804'],
];
const inputs = [];
for (const [name, hash] of sources)
{
    const response = await fetch('https://www.unicode.org/Public/16.0.0/ucd/' + name);
    if (!response.ok) throw Error(name + ': HTTP ' + response.status);
    const text = await response.text();
    if (createHash('sha256').update(text).digest('hex') !== hash) throw Error('数据校验失败：' + name);
    inputs.push(text);
}
const names = { Left_To_Right: 'L', Right_To_Left: 'R', Arabic_Letter: 'AL', European_Terminator: 'ET' };
const classes = Array(0x110000).fill('L');
function assign(line)
{
    const [range, value] = line.split(';').map(value => value.trim());
    const [first, last = first] = range.split('..').map(value => parseInt(value, 16));
    classes.fill(names[value] || value, first, last + 1);
}
for (const match of inputs[0].matchAll(/@missing:\s*([^\n]+)/g)) assign(match[1]);
for (const line of inputs[0].split('\n'))
{
    const value = line.split('#')[0].trim();
    if (value) assign(value);
}
const output = ['// Unicode 16.0.0; generated by scripts/generate_gui_bidi.mjs.',
    'static constexpr bidi_range bidi_ranges[] =', '{'];
for (let first = 0; first < classes.length;)
{
    let end = first + 1;
    while (end < classes.length && classes[first] === classes[end]) ++end;
    output.push(`    {0x${first.toString(16)}, 0x${(end - 1).toString(16)}, bidi_type::${classes[first].toLowerCase()}},`);
    first = end;
}
output.push('};', 'static constexpr bracket_entry bidi_brackets[] =', '{');
for (const line of inputs[1].split('\n'))
{
    const fields = line.split('#')[0].trim().split(';').map(value => value.trim());
    if (fields.length === 3) output.push(`    {0x${fields[0]}, 0x${fields[1]}, ${fields[2] === 'o'}},`);
}
output.push('};', 'static constexpr mirror_entry bidi_mirrors[] =', '{');
for (const line of inputs[2].split('\n'))
{
    const fields = line.split('#')[0].trim().split(';').map(value => value.trim());
    if (fields.length === 2) output.push(`    {0x${fields[0]}, 0x${fields[1]}},`);
}
output.push('};', '');
await writeFile(new URL('../src/stdlib/native_gui/core/bidi_tables.inc', import.meta.url), output.join('\n'), 'utf8');
await writeFile(new URL('../tests/native_gui/data/bidi_test.txt', import.meta.url), inputs[3], 'utf8');
await writeFile(new URL('../tests/native_gui/data/bidi_character_test.txt', import.meta.url), inputs[4], 'utf8');
console.log('Unicode 16.0 bidi properties and official tests verified and generated');
