// Unicode 16.0 固定输入；只生成属性数据，不引入外部断行算法。
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const sources = new Map([
    ['LineBreak.txt', 'e97e4259d0d20fab150b9c7b4b28abfae5cd78ca97e7f4ac6ed20d685d5f4a7c'],
    ['EastAsianWidth.txt', '43adc76c0686a42cb370764eb8cfe2b2a45b10b855e5572a2db4a0eecce15d5b'],
    ['extracted/DerivedGeneralCategory.txt', '7676ab755a41ef82108460238569e60ad65c191ddafe61b36c6765ec1353f293'],
    ['emoji/emoji-data.txt', 'f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a'],
    ['auxiliary/LineBreakTest.txt', '910759a611a479f37df4f535d2e64d7589be3c5ac5f7491cf1fb4fa4cdb211e9'],
]);

function records(text)
{
    return text.split('\n').flatMap(line =>
    {
        const value = line.split('#')[0].trim();
        if (!value) return [];
        const [range, property] = value.split(';').map(field => field.trim());
        const [first, last = first] = range.split('..').map(field => parseInt(field, 16));
        return [{ first, last, property }];
    });
}

export async function generate(inputs)
{
    for (const [name, hash] of sources)
    {
        if (!inputs[name])
        {
            const response = await fetch('https://www.unicode.org/Public/16.0.0/ucd/' + name);
            if (!response.ok) throw Error(name + ': HTTP ' + response.status);
            inputs[name] = await response.text();
        }
        if (createHash('sha256').update(inputs[name]).digest('hex') !== hash)
        {
            throw Error('Unicode source hash mismatch: ' + name);
        }
    }
    const length = 0x110000;
    const classes = Array(length).fill('AL');
    const flags = new Uint8Array(length);
    for (const { first, last, property } of records(inputs['extracted/DerivedGeneralCategory.txt']))
    {
        const bit = { Pi: 1, Pf: 2, Cn: 8, Mn: 32, Mc: 32 }[property] || 0;
        if (bit) flags.fill(bit, first, last + 1);
    }
    for (const { first, last, property } of records(inputs['LineBreak.txt']))
    {
        for (let i = first; i <= last; ++i)
        {
            classes[i] = ['AI', 'SG', 'XX'].includes(property) ? 'AL' : property === 'CJ' ? 'NS' :
                property === 'SA' ? flags[i] & 32 ? 'CM' : 'AL' : property;
        }
    }
    for (const [name, predicate, bit] of [
        ['EastAsianWidth.txt', value => ['F', 'W', 'H'].includes(value), 4],
        ['emoji/emoji-data.txt', value => value === 'Extended_Pictographic', 16],
    ])
    {
        for (const { first, last, property } of records(inputs[name]))
        {
            if (!predicate(property)) continue;
            for (let i = first; i <= last; ++i) flags[i] |= bit;
        }
    }
    // Mn/Mc 已用于 LB1，后续规则仅需五个标志位。
    for (let i = 0; i < length; ++i) flags[i] &= 31;
    const output = ['// Unicode 16.0.0; generated by scripts/generate_gui_line_break.mjs.',
        '// Unicode data license: unicode_license.txt; input SHA-256 pinned in generator.',
        'constexpr line_property_range line_ranges[] =', '{'];
    for (let first = 0; first < length;)
    {
        let end = first + 1;
        while (end < length && classes[end] === classes[first] && flags[end] === flags[first]) ++end;
        output.push(`    {0x${first.toString(16)}, 0x${(end - 1).toString(16)}, line_class::${classes[first].toLowerCase()}, ${flags[first]}},`);
        first = end;
    }
    output.push('};', '');
    const root = new URL('../', import.meta.url);
    await writeFile(new URL('src/stdlib/native_gui/core/line_break_tables.inc', root), output.join('\n'), 'utf8');
    await writeFile(new URL('tests/native_gui/data/line_break_test.txt', root), inputs['auxiliary/LineBreakTest.txt'], 'utf8');
    return { ranges: output.length - 6, classes: [...new Set(classes)].sort() };
}

if (globalThis.process?.argv[1] === fileURLToPath(import.meta.url))
{
    console.log(await generate({}));
}
