// Unicode 标准数据是输入，不包含第三方整形实现。
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';

const files = [
    ['extracted/DerivedJoiningType.txt', '6bd08b97da66b70ccfdab105a352de2984e02625239ec5695422c99b33d854f0'],
    ['Scripts.txt', '9e88f0a677df47311106340be8ede2ecdacd9c1c931831218d2be6d5508e0039'],
    ['PropertyValueAliases.txt', '440fd3e5460b9bfe31da67b6f923992e1989d31fe2ed91e091c4b8f8e2620bf9'],
];
const inputs = [];
for (const [file, hash] of files)
{
    const response = await fetch('https://www.unicode.org/Public/16.0.0/ucd/' + file);
    if (!response.ok) throw Error(file + ': HTTP ' + response.status);
    const text = await response.text();
    if (createHash('sha256').update(text).digest('hex') !== hash) throw Error(file + ': SHA-256 mismatch');
    inputs.push(text);
}
function records(text)
{
    return text.split('\n').map(line => line.split('#')[0].trim()).filter(Boolean)
        .map(line => line.split(';').map(field => field.trim()));
}
function ranges(text, value)
{
    return records(text).map(([range, property]) =>
    {
        const [first, last = first] = range.split('..').map(v => parseInt(v, 16));
        return { first, last, value: value(property) };
    }).sort((a, b) => a.first - b.first);
}
const aliases = new Map(records(inputs[2]).filter(fields => fields[0] === 'sc').map(fields => [fields[2], fields[1]]));
const output = ['// Unicode 16.0; generated by scripts/generate_gui_shaping.mjs.',
    'static constexpr joining_range joining_ranges[] =', '{'];
for (const range of ranges(inputs[0], value => value.toLowerCase()))
{
    output.push(`    {0x${range.first.toString(16)}, 0x${range.last.toString(16)}, '${range.value}'},`);
}
output.push('};', 'static constexpr script_range script_ranges[] =', '{');
for (const range of ranges(inputs[1], value => aliases.get(value)))
{
    if (['Zyyy', 'Zinh', 'Zzzz'].includes(range.value)) continue;
    const special = { Hira: 'kana', Hrkt: 'kana', Laoo: 'lao ', Yiii: 'yi  ', Nkoo: 'nko ', Vaii: 'vai ' };
    const tag = special[range.value] || range.value.toLowerCase();
    output.push(`    {0x${range.first.toString(16)}, 0x${range.last.toString(16)}, ot_tag("${tag}")},`);
}
output.push('};', '');
await writeFile(new URL('../src/stdlib/native_gui/core/shaping_tables.inc', import.meta.url), output.join('\n'), 'utf8');
console.log('Unicode 16.0 shaping properties verified and generated');
