#include "backend/llvm/codegen.hpp"

namespace tx
{

void llvm_code_generator::write_gui_declarations()
{
    module_
        << "declare i32 @txrt_gui_fixed(double, ptr, ptr)\n"
        << "declare i32 @txrt_gui_auto_length(ptr, ptr)\n"
        << "declare i32 @txrt_gui_stretch(double, ptr, ptr)\n"
        << "declare i32 @txrt_gui_root(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_create_container(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_create_label(ptr, ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_create_button(ptr, ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_create_text_box(ptr, i1, ptr, ptr)\n"
        << "declare i32 @txrt_gui_create_check_box(ptr, ptr, i1, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_column(ptr, double, double)\n"
        << "declare i32 @txrt_gui_set_row(ptr, double, double)\n"
        << "declare i32 @txrt_gui_set_grid(ptr, i64, i64, double, double)\n"
        << "declare i32 @txrt_gui_set_grid_row(ptr, i64, ptr, double)\n"
        << "declare i32 @txrt_gui_set_grid_column(ptr, i64, ptr, double)\n"
        << "declare i32 @txrt_gui_flush_layout(ptr)\n"
        << "declare i32 @txrt_gui_set_default_button(ptr)\n"
        << "declare i32 @txrt_gui_set_cancel_button(ptr)\n"
        << "declare i32 @txrt_gui_set_checked(ptr, i1)\n"
        << "declare i32 @txrt_gui_checked(ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_check_state(ptr, ptr)\n"
        << "declare i32 @txrt_gui_check_state(ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_read_only(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_password(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_text_limit(ptr, i64)\n"
        << "declare i32 @txrt_gui_set_selection(ptr, i64, i64)\n"
        << "declare i32 @txrt_gui_selection_start(ptr, ptr)\n"
        << "declare i32 @txrt_gui_selection_end(ptr, ptr)\n"
        << "declare i32 @txrt_gui_id_container(ptr, ptr)\n"
        << "declare i32 @txrt_gui_is_open_container(ptr, ptr)\n"
        << "declare i32 @txrt_gui_close_container(ptr)\n"
        << "declare i32 @txrt_gui_set_enabled_container(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_visible_container(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_reserved_space_container(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_width_container(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_height_container(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_constraints_container(ptr, double, double, double, double)\n"
        << "declare i32 @txrt_gui_set_margin_container(ptr, double)\n"
        << "declare i32 @txrt_gui_set_alignment_container(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_cell_container(ptr, i64, i64, i64, i64)\n"
        << "declare i32 @txrt_gui_id_label(ptr, ptr)\n"
        << "declare i32 @txrt_gui_is_open_label(ptr, ptr)\n"
        << "declare i32 @txrt_gui_close_label(ptr)\n"
        << "declare i32 @txrt_gui_set_enabled_label(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_visible_label(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_reserved_space_label(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_width_label(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_height_label(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_constraints_label(ptr, double, double, double, double)\n"
        << "declare i32 @txrt_gui_set_margin_label(ptr, double)\n"
        << "declare i32 @txrt_gui_set_alignment_label(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_cell_label(ptr, i64, i64, i64, i64)\n"
        << "declare i32 @txrt_gui_set_text_label(ptr, ptr)\n"
        << "declare i32 @txrt_gui_text_label(ptr, ptr)\n"
        << "declare i32 @txrt_gui_id_button(ptr, ptr)\n"
        << "declare i32 @txrt_gui_is_open_button(ptr, ptr)\n"
        << "declare i32 @txrt_gui_close_button(ptr)\n"
        << "declare i32 @txrt_gui_set_enabled_button(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_visible_button(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_reserved_space_button(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_width_button(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_height_button(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_constraints_button(ptr, double, double, double, double)\n"
        << "declare i32 @txrt_gui_set_margin_button(ptr, double)\n"
        << "declare i32 @txrt_gui_set_alignment_button(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_cell_button(ptr, i64, i64, i64, i64)\n"
        << "declare i32 @txrt_gui_set_text_button(ptr, ptr)\n"
        << "declare i32 @txrt_gui_text_button(ptr, ptr)\n"
        << "declare i32 @txrt_gui_focus_button(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_id_text_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_is_open_text_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_close_text_box(ptr)\n"
        << "declare i32 @txrt_gui_set_enabled_text_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_visible_text_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_reserved_space_text_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_width_text_box(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_height_text_box(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_constraints_text_box(ptr, double, double, double, double)\n"
        << "declare i32 @txrt_gui_set_margin_text_box(ptr, double)\n"
        << "declare i32 @txrt_gui_set_alignment_text_box(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_cell_text_box(ptr, i64, i64, i64, i64)\n"
        << "declare i32 @txrt_gui_set_text_text_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_text_text_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_focus_text_box(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_id_check_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_is_open_check_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_close_check_box(ptr)\n"
        << "declare i32 @txrt_gui_set_enabled_check_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_visible_check_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_reserved_space_check_box(ptr, i1)\n"
        << "declare i32 @txrt_gui_set_width_check_box(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_height_check_box(ptr, ptr, double)\n"
        << "declare i32 @txrt_gui_set_constraints_check_box(ptr, double, double, double, double)\n"
        << "declare i32 @txrt_gui_set_margin_check_box(ptr, double)\n"
        << "declare i32 @txrt_gui_set_alignment_check_box(ptr, ptr, ptr)\n"
        << "declare i32 @txrt_gui_set_cell_check_box(ptr, i64, i64, i64, i64)\n"
        << "declare i32 @txrt_gui_set_text_check_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_text_check_box(ptr, ptr)\n"
        << "declare i32 @txrt_gui_focus_check_box(ptr, ptr, ptr)\n"
        ;
}

} // namespace tx
