#include "backend/llvm/codegen.hpp"

namespace tx
{

void llvm_code_generator::write_external_declarations()
{
    module_ << "declare i32 @txrt_math_abs_i64(i64, ptr)\n"
            << "declare i32 @txrt_math_abs_f64(double, ptr)\n"
            << "declare i32 @txrt_math_min_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_min_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_max_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_max_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_clamp_i64(i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_math_clamp_f64(double, double, double, ptr)\n"
            << "declare i32 @txrt_math_mod_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_sqrt_f64(double, ptr)\n"
            << "declare i32 @txrt_math_pow_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_floor_f64(double, ptr)\n"
            << "declare i32 @txrt_math_ceil_f64(double, ptr)\n"
            << "declare i32 @txrt_random_seed_i64(i64)\n"
            << "declare i32 @txrt_random_int_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_random_float_f64(ptr)\n"
            << "declare i64 @txrt_random_int_direct(i64, i64)\n"
            << "declare double @txrt_random_float_direct()\n"
            << "declare ptr @txrt_random_context()\n"
            << "declare i32 @txrt_random_seed_context(ptr, i64)\n"
            << "declare i64 @txrt_random_int_context(ptr, i64, i64)\n"
            << "declare double @txrt_random_float_context(ptr)\n\n";
    module_ << "declare i32 @txrt_string_contains(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_starts_with(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_ends_with(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_find(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_slice(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_string_replace(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_split(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_join(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_trim(ptr, ptr)\n"
            << "declare i32 @txrt_string_lower(ptr, ptr)\n"
            << "declare i32 @txrt_string_upper(ptr, ptr)\n"
            << "declare i32 @txrt_format_format(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_array_concat(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_array_slice(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_array_reverse(ptr, ptr)\n"
            << "declare i32 @txrt_file_read_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_write_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_append_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_fs_exists(ptr, ptr)\n"
            << "declare i32 @txrt_fs_is_file(ptr, ptr)\n"
            << "declare i32 @txrt_fs_is_directory(ptr, ptr)\n"
            << "declare i32 @txrt_fs_create_directories(ptr)\n"
            << "declare i32 @txrt_fs_list_directory(ptr, ptr)\n"
            << "declare i32 @txrt_path_join(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_path_parent(ptr, ptr)\n"
            << "declare i32 @txrt_path_file_name(ptr, ptr)\n"
            << "declare i32 @txrt_path_extension(ptr, ptr)\n"
            << "declare i32 @txrt_io_write(ptr)\n"
            << "declare i32 @txrt_io_write_line(ptr)\n"
            << "declare i32 @txrt_io_write_error(ptr)\n"
            << "declare i32 @txrt_io_flush()\n"
            << "declare i32 @txrt_time_unix_millis(ptr)\n"
            << "declare i32 @txrt_time_monotonic_millis(ptr)\n"
            << "declare i32 @txrt_time_monotonic_micros(ptr)\n"
            << "declare i32 @txrt_time_sleep_millis(i64)\n\n";
}

} // namespace tx
