#include "backend/llvm/codegen.hpp"

#include <algorithm>

namespace tx
{

void llvm_code_generator::write_external_declarations()
{
    for (const auto& [name, overloads] : functions_)
    {
        (void)name;
        for (std::size_t index = 0; index < overloads.size(); ++index)
        {
            const auto& function = *overloads[index];
            if (!function.external_name.starts_with("requests."))
            {
                continue;
            }
            bool method = false;
            std::string symbol;
            if (function.external_name.starts_with("requests.session."))
            {
                symbol = "m0_bridge_session_" +
                    function.external_name.substr(17);
                method = true;
            }
            else if (function.external_name.starts_with("requests.response."))
            {
                symbol = "m0_bridge_" + function.external_name.substr(18);
                method = true;
            }
            else if (function.external_name.find('.', 9) == std::string::npos)
            {
                symbol = "m0_bridge_" + function.external_name.substr(9);
            }
            else
            {
                continue;
            }
            const auto implementation = functions_.find(symbol);
            if (implementation != functions_.end() &&
                std::any_of(implementation->second.begin(),
                    implementation->second.end(),
                    [](const function_decl* item) { return !item->external; }))
            {
                continue;
            }
            module_ << "declare " << llvm_type(function.return_type,
                function.position) << ' '
                << function_name(symbol, index) << "(ptr";
            if (method)
            {
                module_ << ", ptr";
            }
            for (std::size_t parameter = 0;
                 parameter < function.parameters.size(); ++parameter)
            {
                module_ << ", ";
                module_ << llvm_type(parameter_abi_type(
                                         function.parameters[parameter]),
                                     function.parameters[parameter].position);
            }
            module_ << ")\n";
        }
    }
    write_vector_declarations();
    write_sum_declarations();
    write_iterator_declarations();
    write_container_declarations();
    write_algorithm_declarations();
    write_sync_declarations();
    write_channel_declarations();
    module_ << "declare i32 @txrt_parse_try_parse_int(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_parse_int_scalar(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_parse_float_scalar(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_parse_materialize_int(i1, i64, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_parse_materialize_float(i1, double, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_call_needs_default(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_parse_try_parse_float(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_parse_parse_int(ptr, i64, ptr)\n"
            << "declare i32 @txrt_parse_parse_float(ptr, ptr)\n"
            << "declare i32 @txrt_json_parse(ptr, ptr)\n"
            << "declare i32 @txrt_json_parse_object(ptr, ptr)\n"
            << "declare i32 @txrt_json_try_parse(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_stringify(ptr, ptr)\n"
            << "declare i32 @txrt_json_stringify_pretty(ptr, i64, ptr)\n"
            << "declare i32 @txrt_json_contains(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_int(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_float(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_bool(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_str(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_array(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_get_object(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_default_limits(ptr, ptr)\n"
            << "declare i32 @txrt_json_read_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_read_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_reader_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_reader_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_next(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_write_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_write_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_writer_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_writer_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_json_write_value(ptr, ptr)\n"
            << "declare i32 @txrt_json_finish(ptr)\n"
            << "declare i32 @txrt_json_close_reader(ptr)\n"
            << "declare i32 @txrt_json_close_writer(ptr)\n"
            << "declare i32 @txrt_json_validate(ptr, ptr)\n"
            << "declare i32 @txrt_serde_serialize_json(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_format_begin(ptr, i64, ptr, i64)\n"
            << "declare i32 @txrt_encoding_encode_known(ptr, i64, ptr)\n"
            << "declare i32 @txrt_encoding_decode_known(ptr, i64, ptr)\n"
            << "declare i32 @txrt_format_append_i64(ptr, i64, ptr, i8, ptr, i64)\n"
            << "declare i32 @txrt_format_append_f64(ptr, double, ptr, i8, ptr, i64)\n"
            << "declare i32 @txrt_format_append_bool(ptr, i1, ptr, i8, ptr, i64)\n"
            << "declare i32 @txrt_format_append_str(ptr, ptr, ptr, i8, ptr, i64)\n"
            << "declare i32 @txrt_format_plain_i64(ptr, i64, ptr, i64)\n"
            << "declare i32 @txrt_format_plain_bool(ptr, i1, ptr, i64)\n"
            << "declare i32 @txrt_format_plain_str(ptr, ptr, ptr, i64)\n"
            << "declare i32 @txrt_format_plain_bytes(ptr, ptr, i64, ptr, i64)\n"
            << "declare void @txrt_format_finish(ptr)\n"
            << "declare i32 @txrt_serde_deserialize_json(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_serde_serialize_cbor(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_serde_deserialize_cbor(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_default_limits(ptr, ptr)\n"
            << "declare i32 @txrt_cbor_encode(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_decode(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_read(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_write(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_reader(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_next(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_writer(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_cbor_write_value(ptr, ptr)\n"
            << "declare i32 @txrt_cbor_finish(ptr)\n"
            << "declare i32 @txrt_cbor_close_reader(ptr)\n"
            << "declare i32 @txrt_cbor_close_writer(ptr)\n"
            << "declare i32 @txrt_csv_default_dialect(ptr, ptr)\n"
            << "declare i32 @txrt_csv_reader_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_reader_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_next_row(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_header(ptr, ptr)\n"
            << "declare i32 @txrt_csv_writer_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_writer_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_write_row(ptr, ptr)\n"
            << "declare i32 @txrt_csv_finish(ptr)\n"
            << "declare i32 @txrt_csv_close_reader(ptr)\n"
            << "declare i32 @txrt_csv_close_writer(ptr)\n"
            << "declare i32 @txrt_csv_parse(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_csv_stringify(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_default_limits(ptr, ptr)\n"
            << "declare i32 @txrt_xml_reader_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_reader_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_next(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_attribute_count_reader(ptr, ptr)\n"
            << "declare i32 @txrt_xml_attribute_local_name_reader(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_namespace_uri_reader(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_prefix_reader(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_value_reader(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_close_reader(ptr)\n"
            << "declare i32 @txrt_xml_parse(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_read_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_read_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_root(ptr, ptr)\n"
            << "declare i32 @txrt_xml_first_child(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_next_sibling(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_kind(ptr, ptr)\n"
            << "declare i32 @txrt_xml_local_name(ptr, ptr)\n"
            << "declare i32 @txrt_xml_namespace_uri(ptr, ptr)\n"
            << "declare i32 @txrt_xml_prefix(ptr, ptr)\n"
            << "declare i32 @txrt_xml_text(ptr, ptr)\n"
            << "declare i32 @txrt_xml_attribute_count_node(ptr, ptr)\n"
            << "declare i32 @txrt_xml_attribute_local_name_node(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_namespace_uri_node(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_prefix_node(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_attribute_value_node(ptr, i64, ptr)\n"
            << "declare i32 @txrt_xml_new_document(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_append_element(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_set_attribute(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_append_text(ptr, ptr)\n"
            << "declare i32 @txrt_xml_stringify(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_write_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_write_text_stream(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_writer_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_writer_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_start_element(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_write_attribute(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_xml_write_text(ptr, ptr)\n"
            << "declare i32 @txrt_xml_end_element(ptr)\n"
            << "declare i32 @txrt_xml_finish(ptr)\n"
            << "declare i32 @txrt_xml_close_writer(ptr)\n"
            << "declare i32 @txrt_file_try_read_text(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_try_write_text(ptr, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_try_append_text(ptr, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_bytes_empty(ptr)\n"
            << "declare i32 @txrt_bytes_from_vector(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_to_vector(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_concat(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_bytes_slice(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_bytes_to_hex(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_from_hex(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_to_base64(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_from_base64(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_to_base64_url(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_from_base64_url(ptr, ptr)\n"
            << "declare i32 @txrt_bytes_to_hex_chunk(ptr, i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_bytes_to_base64_chunk(ptr, i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_bytes_at(ptr, i64, ptr)\n"
            << "declare i32 @txrt_bytes_equal(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_random_bytes(i64, ptr)\n"
            << "declare i32 @txrt_crypto_generate_key(ptr)\n"
            << "declare i32 @txrt_crypto_sha256(ptr, ptr)\n"
            << "declare i32 @txrt_crypto_sha512(ptr, ptr)\n"
            << "declare i32 @txrt_crypto_hmac_sha256(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_secure_equal(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_hkdf_sha256(ptr, ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_crypto_pbkdf2_sha256(ptr, ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_crypto_encrypt(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_decrypt(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_sha256_stream(ptr, ptr)\n"
            << "declare i32 @txrt_crypto_sha512_stream(ptr, ptr)\n"
            << "declare i32 @txrt_crypto_hmac_sha256_stream(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_encrypt_file(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_decrypt_file(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_crypto_file_key_id(ptr, ptr)\n"
            << "declare i32 @txrt_secret_from_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_secret_random(i64, ptr)\n"
            << "declare i32 @txrt_secret_to_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_secret_size(ptr, ptr)\n"
            << "declare i32 @txrt_secret_equal(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_secret_close(ptr)\n"
            << "declare i32 @txrt_password_hash_password(ptr, ptr)\n"
            << "declare i32 @txrt_password_hash_password_with_params(ptr, i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_password_verify_password(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_password_needs_rehash(ptr, i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_public_key_ed25519_generate(ptr)\n"
            << "declare i32 @txrt_public_key_ed25519_import_seed(ptr, ptr)\n"
            << "declare i32 @txrt_public_key_ed25519_public(ptr, ptr)\n"
            << "declare i32 @txrt_public_key_ed25519_sign(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_public_key_ed25519_verify(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_public_key_x25519_generate(ptr)\n"
            << "declare i32 @txrt_public_key_x25519_import_private(ptr, ptr)\n"
            << "declare i32 @txrt_public_key_x25519_public(ptr, ptr)\n"
            << "declare i32 @txrt_public_key_x25519_derive(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_x509_parse_pem(ptr, ptr)\n"
            << "declare i32 @txrt_x509_parse_der(ptr, ptr)\n"
            << "declare i32 @txrt_x509_parse_pkcs12(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_x509_pkcs12_private_key(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_x509_verify(ptr, ptr, ptr, ptr, ptr, i1, ptr, ptr)\n"
            << "declare i32 @txrt_dns_resolve(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_dns_resolve_with_cancel(ptr, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_listen_tcp(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_listener_port(ptr, ptr)\n"
            << "declare i32 @txrt_socket_connect_tcp(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_accept_tcp(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_connect_async(ptr, i64, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_accept_async(ptr, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_read(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_write(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_socket_read_async(ptr, i64, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_write_async(ptr, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_shutdown_read(ptr)\n"
            << "declare i32 @txrt_socket_shutdown_write(ptr)\n"
            << "declare i32 @txrt_socket_bind_udp(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_udp_port(ptr, ptr)\n"
            << "declare i32 @txrt_socket_send_to(ptr, ptr, i64, ptr, i64, ptr)\n"
            << "declare i32 @txrt_socket_receive_from(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_socket_send_to_async(ptr, ptr, i64, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_receive_from_async(ptr, i64, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_socket_close_tcp_listener(ptr)\n"
            << "declare i32 @txrt_socket_close_tcp_stream(ptr)\n"
            << "declare i32 @txrt_socket_close_udp_socket(ptr)\n"
            << "declare i32 @txrt_tls_system_trust(ptr, ptr)\n"
            << "declare i32 @txrt_tls_custom_trust(ptr, i1, ptr, ptr)\n"
            << "declare i32 @txrt_tls_import_identity(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_tls_close_identity(ptr)\n"
            << "declare i32 @txrt_tls_client(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_tls_with_client_identity(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_tls_server(ptr, ptr, i1, ptr, ptr)\n"
            << "declare i32 @txrt_tls_verify_server(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_tls_verify_client(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_tls_connect(ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_tls_accept(ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_tls_read(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_tls_write(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_tls_negotiated_alpn(ptr, ptr)\n"
            << "declare i32 @txrt_tls_close(ptr, i64)\n"
            << "declare i32 @txrt_encoding_encode(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_encoding_decode(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_encoding_new_decoder(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_encoding_decode_chunk(ptr, ptr, i1, ptr)\n"
            << "declare i32 @txrt_encoding_decoder_replacements(ptr, ptr)\n"
            << "declare i32 @txrt_encoding_new_encoder(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_encoding_encode_chunk(ptr, ptr, i1, ptr)\n"
            << "declare i32 @txrt_encoding_encoder_replacements(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_version(ptr)\n"
            << "declare i32 @txrt_unicode_icu_version(ptr)\n"
            << "declare i32 @txrt_unicode_normalize(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_unicode_case_fold(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_to_lower(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_unicode_to_upper(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_unicode_code_points(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_graphemes(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_grapheme_count(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_category(i64, ptr)\n"
            << "declare i32 @txrt_unicode_display_width(ptr, ptr)\n"
            << "declare i32 @txrt_unicode_compare(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_regex_compile(ptr, ptr, i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_regex_compile_with_cancel(ptr, ptr, i64, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_regex_search(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_regex_match(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_regex_full_match(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_regex_find_all(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_regex_replace(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_regex_split(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_open_binary(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_open_binary_shared(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_read_bytes(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_read_all_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_write_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_tell(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_seek(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_flush_binary(ptr)\n"
            << "declare i32 @txrt_file_stream_sync_binary(ptr)\n"
            << "declare i32 @txrt_file_stream_lock(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_try_lock(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_unlock(ptr)\n"
            << "declare i32 @txrt_file_stream_close_binary(ptr)\n"
            << "declare i32 @txrt_file_stream_open_text(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_read_chars(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_read_line(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_write_text(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_write_line(ptr, ptr)\n"
            << "declare i32 @txrt_file_stream_flush_text(ptr)\n"
            << "declare i32 @txrt_file_stream_sync_text(ptr)\n"
            << "declare i32 @txrt_file_stream_close_text(ptr)\n"
            << "declare i32 @txrt_error_status()\n"
            << "declare void @txrt_error_propagation(i1)\n"
            << "declare i32 @txrt_error_take(ptr, ptr)\n"
            << "declare i32 @txrt_error_fail_io(ptr, ptr)\n";
    module_ << "declare i32 @txrt_error_stack_trace(ptr)\n"
            << "declare void @txrt_stack_error_location(ptr, ptr, i64, i64)\n";
    module_ << "declare i32 @txrt_test_assert_true(i1, ptr)\n"
            << "declare i32 @txrt_test_assert_false(i1, ptr)\n"
            << "declare i32 @txrt_test_assert_equal_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_test_assert_equal_f64(double, double, ptr)\n"
            << "declare i32 @txrt_test_assert_equal_bool(i1, i1, ptr)\n"
            << "declare i32 @txrt_test_assert_equal_str(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_test_assert_near(double, double, double, ptr)\n"
            << "declare i32 @txrt_test_assert_throws(ptr)\n"
            << "declare i32 @txrt_test_assert_throws_code(ptr, ptr)\n"
            << "declare i32 @txrt_test_run_case(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_test_failures(ptr)\n"
            << "declare i32 @txrt_test_temp_directory(ptr)\n"
            << "declare i32 @txrt_test_seed(i64)\n";
    module_ << "declare i32 @txrt_log_event(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_log_event_redacted(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_log_set_context(ptr, ptr)\n";
    module_ << "declare i32 @txrt_debug_stack_trace(ptr)\n"
            << "declare i32 @txrt_debug_last_error_stack(ptr)\n"
            << "declare i32 @txrt_debug_location(ptr)\n"
            << "declare i32 @txrt_debug_dump_i64(i64)\n"
            << "declare i32 @txrt_debug_dump_f64(double)\n"
            << "declare i32 @txrt_debug_dump_bool(i1)\n"
            << "declare i32 @txrt_debug_dump_str(ptr)\n";
    module_ << "declare i32 @txrt_cancel_source(ptr)\n"
            << "declare i32 @txrt_cancel_with_deadline_ms(i64, ptr)\n"
            << "declare i32 @txrt_cancel_token(ptr, ptr)\n"
            << "declare i32 @txrt_cancel_cancel(ptr, ptr)\n"
            << "declare i32 @txrt_cancel_status(ptr, ptr)\n"
            << "declare i32 @txrt_cancel_wait(ptr, i64, ptr)\n";
    module_ << "declare i32 @txrt_thread_spawn(ptr, i64, ptr)\n"
            << "declare i32 @txrt_thread_join_void(ptr)\n"
            << "declare i32 @txrt_thread_join_i64(ptr, ptr)\n"
            << "declare i32 @txrt_thread_join_f64(ptr, ptr)\n"
            << "declare i32 @txrt_thread_join_bool(ptr, ptr)\n"
            << "declare i32 @txrt_thread_join_str(ptr, ptr)\n"
            << "declare i32 @txrt_thread_join_value(ptr, ptr)\n"
            << "declare i32 @txrt_thread_detach(ptr)\n"
            << "declare i32 @txrt_thread_id(ptr, ptr)\n"
            << "declare i32 @txrt_thread_take_detached_error(ptr)\n";
    module_ << "declare i32 @txrt_task_scope_void(ptr, i64, i64)\n"
            << "declare i32 @txrt_task_scope_i64(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_task_scope_f64(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_task_scope_bool(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_task_scope_str(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_task_scope_value(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_task_spawn(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_task_spawn_current(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_task_wait_void(ptr)\n"
            << "declare i32 @txrt_task_wait_i64(ptr, ptr)\n"
            << "declare i32 @txrt_task_wait_f64(ptr, ptr)\n"
            << "declare i32 @txrt_task_wait_bool(ptr, ptr)\n"
            << "declare i32 @txrt_task_wait_str(ptr, ptr)\n"
            << "declare i32 @txrt_task_wait_value(ptr, ptr)\n"
            << "declare i32 @txrt_task_cancel(ptr, ptr)\n"
            << "declare i32 @txrt_task_token(ptr, ptr)\n"
            << "declare i32 @txrt_task_current_token(ptr)\n"
            << "declare i32 @txrt_task_after(ptr, i64, ptr)\n"
            << "declare i32 @txrt_task_sleep(i64, ptr)\n";
    module_ << "declare i32 @txrt_str_concat_literal(ptr, ptr, i64, i1, ptr)\n";
    module_ << "declare i32 @txrt_string_split_vector_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_join_vector_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_join_literal(ptr, ptr, i64, ptr)\n";
    module_ << "declare i32 @txrt_dictionary_get_concat(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_dictionary_get_i64(ptr, i64, ptr)\n"
            << "declare i32 @txrt_dictionary_contains_i64(ptr, i64, ptr)\n"
            << "declare i32 @txrt_dictionary_remove_i64(ptr, i64, ptr)\n"
            << "declare i32 @txrt_dictionary_get_f64(ptr, double, ptr)\n"
            << "declare i32 @txrt_dictionary_contains_f64(ptr, double, ptr)\n"
            << "declare i32 @txrt_dictionary_remove_f64(ptr, double, ptr)\n"
            << "declare i32 @txrt_dictionary_get_bool(ptr, i1, ptr)\n"
            << "declare i32 @txrt_dictionary_contains_bool(ptr, i1, ptr)\n"
            << "declare i32 @txrt_dictionary_remove_bool(ptr, i1, ptr)\n"
            << "declare i32 @txrt_dictionary_contains_concat(ptr, ptr, ptr, ptr)\n";
    module_ << "declare i32 @txrt_math_abs_i64(i64, ptr)\n"
            << "declare i32 @txrt_math_abs_f64(double, ptr)\n"
            << "declare i32 @txrt_math_min_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_min_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_max_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_max_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_clamp_i64(i64, i64, i64, ptr)\n"
            << "declare i32 @txrt_math_clamp_f64(double, double, double, ptr)\n"
            << "declare i32 @txrt_math_mod_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_sqrt_f64(double, ptr)\n"
            << "declare i32 @txrt_math_pow_f64(double, double, ptr)\n"
            << "declare i32 @txrt_math_floor_f64(double, ptr)\n"
            << "declare i32 @txrt_math_ceil_f64(double, ptr)\n"
            << "declare i32 @txrt_math_atan2(double, double, ptr)\n"
            << "declare i32 @txrt_math_gcd(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_lcm(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_pow_int(i64, i64, ptr)\n"
            << "declare i32 @txrt_math_round_to_int(double, ptr, ptr)\n"
            << "declare i32 @txrt_random_seed_i64(i64)\n"
            << "declare i32 @txrt_random_int_i64(i64, i64, ptr)\n"
            << "declare i32 @txrt_random_float_f64(ptr)\n"
            << "declare i64 @txrt_random_int_direct(i64, i64)\n"
            << "declare double @txrt_random_float_direct()\n"
            << "declare ptr @txrt_random_context()\n"
            << "declare i32 @txrt_random_seed_context(ptr, i64)\n"
            << "declare i32 @txrt_random_int_context(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_random_float_context(ptr, ptr)\n\n";
    for (const auto* name : {"sin", "cos", "tan", "asin", "acos", "atan",
                             "sinh", "cosh", "tanh", "exp", "log", "log10"})
    {
        module_ << "declare i32 @txrt_math_" << name << "(double, ptr)\n";
    }
    for (const auto* name : {"is_finite", "is_nan", "is_infinite"})
    {
        module_ << "declare i32 @txrt_math_" << name << "(double, ptr)\n";
    }
    for (const auto* source : {"vector", "iterator"})
    {
        for (const auto* name : {"mean", "median", "variance_population",
                                 "variance_sample", "stdev_population",
                                 "stdev_sample", "frequencies"})
        {
            module_ << "declare i32 @txrt_statistics_" << name << "_"
                    << source << "(ptr, ptr)\n";
        }
        module_ << "declare i32 @txrt_statistics_quantile_" << source
                << "(ptr, double, ptr)\n"
                << "declare i32 @txrt_statistics_histogram_" << source
                << "(ptr, double, double, i64, ptr, ptr)\n";
    }
    module_ << "declare i32 @txrt_statistics_new_accumulator(ptr, ptr)\n"
            << "declare i32 @txrt_statistics_add(ptr, double)\n"
            << "declare i32 @txrt_statistics_count(ptr, ptr)\n";
    for (const auto* name : {"mean_of", "variance_population_of",
                             "variance_sample_of", "stdev_population_of",
                             "stdev_sample_of"})
    {
        module_ << "declare i32 @txrt_statistics_" << name << "(ptr, ptr)\n";
    }
    module_ << "declare i32 @txrt_decimal_parse(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_decimal_from_int(i64, ptr, ptr)\n"
            << "declare i32 @txrt_decimal_to_text(ptr, ptr)\n"
            << "declare i32 @txrt_decimal_scale(ptr, ptr)\n"
            << "declare i32 @txrt_decimal_quantize(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_decimal_compare(ptr, ptr, ptr)\n";
    for (const auto* name : {"add", "sub", "mul", "div"})
    {
        module_ << "declare i32 @txrt_decimal_" << name
                << "(ptr, ptr, i64, ptr, ptr, ptr)\n";
    }
    module_ << "declare i32 @txrt_random_make_generator(i64, ptr, ptr)\n"
            << "declare i32 @txrt_random_reseed(ptr, i64)\n"
            << "declare i32 @txrt_random_algorithm_version(ptr)\n"
            << "declare i32 @txrt_random_next_int(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_random_next_float(ptr, ptr)\n"
            << "declare i32 @txrt_random_bernoulli(ptr, double, ptr)\n"
            << "declare i32 @txrt_random_normal(ptr, double, double, ptr)\n"
            << "declare i32 @txrt_random_exponential(ptr, double, ptr)\n";
    for (const auto* suffix : {"i64", "f64", "bool", "str", "bytes", "object"})
    {
        module_ << "declare i32 @txrt_random_shuffle_" << suffix
                << "(ptr, ptr, ptr)\n"
                << "declare i32 @txrt_random_sample_" << suffix
                << "(ptr, ptr, i64, ptr)\n"
                << "declare i32 @txrt_random_choice_" << suffix
                << "(ptr, ptr, ptr)\n";
    }
    module_ << "declare i32 @txrt_string_contains(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_starts_with(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_ends_with(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_find(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_slice(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_string_replace(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_split(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_join(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_string_contains_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_starts_with_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_ends_with_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_find_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_split_literal(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_replace_literal(ptr, ptr, i64, ptr, i64, ptr)\n"
            << "declare i32 @txrt_string_trim(ptr, ptr)\n"
            << "declare i32 @txrt_string_lower(ptr, ptr)\n"
            << "declare i32 @txrt_string_upper(ptr, ptr)\n"
            << "declare i32 @txrt_format_format(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_array_concat(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_array_slice(ptr, i64, i64, ptr)\n"
            << "declare i32 @txrt_array_reverse(ptr, ptr)\n"
            << "declare i32 @txrt_array_push_back(ptr, ptr)\n"
            << "declare i32 @txrt_array_pop_back(ptr)\n"
            << "declare i32 @txrt_array_insert(ptr, i64, ptr)\n"
            << "declare i32 @txrt_array_erase(ptr, i64)\n"
            << "declare i32 @txrt_array_clear(ptr)\n"
            << "declare i32 @txrt_dictionary_items(ptr, ptr)\n"
            << "declare i32 @txrt_file_read_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_write_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_append_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_file_read_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_file_write_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_file_atomic_write_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_file_atomic_write_text(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_async_file_read_at(ptr, i64, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_async_file_write_at(ptr, i64, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_fs_exists(ptr, ptr)\n"
            << "declare i32 @txrt_fs_is_file(ptr, ptr)\n"
            << "declare i32 @txrt_fs_is_directory(ptr, ptr)\n"
            << "declare i32 @txrt_fs_create_directories(ptr)\n"
            << "declare i32 @txrt_fs_list_directory(ptr, ptr)\n"
            << "declare i32 @txrt_fs_list_directory_vector(ptr, ptr)\n"
            << "declare i32 @txrt_fs_walk_directory(ptr, ptr)\n"
            << "declare i32 @txrt_fs_copy_file(ptr, ptr, i1)\n"
            << "declare i32 @txrt_fs_rename(ptr, ptr)\n"
            << "declare i32 @txrt_fs_remove(ptr, ptr)\n"
            << "declare i32 @txrt_fs_remove_all(ptr, ptr)\n"
            << "declare i32 @txrt_fs_file_size(ptr, ptr)\n"
            << "declare i32 @txrt_fs_modified_millis(ptr, ptr)\n"
            << "declare i32 @txrt_fs_stat(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_fs_lstat(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_fs_set_permissions(ptr, i64)\n"
            << "declare i32 @txrt_fs_create_symlink(ptr, ptr, i1)\n"
            << "declare i32 @txrt_fs_read_symlink(ptr, ptr)\n"
            << "declare i32 @txrt_fs_list_directory_filtered(ptr, ptr, ptr, i1, ptr)\n"
            << "declare i32 @txrt_fs_watch(ptr, i1, ptr)\n"
            << "declare i32 @txrt_fs_watch_next(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_fs_close_watch(ptr)\n"
            << "declare i32 @txrt_process_make_options(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_process_spawn(ptr, ptr)\n"
            << "declare i32 @txrt_process_id(ptr, ptr)\n"
            << "declare i32 @txrt_process_wait(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_process_wait_with_cancel(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_process_try_wait(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_process_terminate(ptr)\n"
            << "declare i32 @txrt_process_kill(ptr)\n"
            << "declare i32 @txrt_process_close(ptr)\n"
            << "declare i32 @txrt_process_stdin_pipe(ptr, ptr)\n"
            << "declare i32 @txrt_process_stdout_pipe(ptr, ptr)\n"
            << "declare i32 @txrt_process_stderr_pipe(ptr, ptr)\n"
            << "declare i32 @txrt_process_close_pipe(ptr)\n"
            << "declare i32 @txrt_process_read_pipe(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_process_write_pipe(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_process_make_limits(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_process_run(ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_process_run_with_cancel(ptr, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ipc_listen(ptr, i64, ptr)\n"
            << "declare i32 @txrt_ipc_accept(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ipc_connect(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ipc_from_process_pipes(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_ipc_send(ptr, i64, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ipc_recv(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ipc_close(ptr, ptr)\n"
            << "declare i32 @txrt_ipc_close_listener(ptr, ptr)\n"
            << "declare i32 @txrt_path_join(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_path_parent(ptr, ptr)\n"
            << "declare i32 @txrt_path_file_name(ptr, ptr)\n"
            << "declare i32 @txrt_path_extension(ptr, ptr)\n"
            << "declare i32 @txrt_path_normalize(ptr, ptr)\n"
            << "declare i32 @txrt_path_is_absolute(ptr, ptr)\n"
            << "declare i32 @txrt_path_absolute(ptr, ptr)\n"
            << "declare i32 @txrt_path_relative(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_path_replace_extension(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_path_canonical(ptr, ptr)\n"
            << "declare i32 @txrt_path_weakly_canonical(ptr, ptr)\n"
            << "declare i32 @txrt_path_root_name(ptr, ptr)\n"
            << "declare i32 @txrt_path_root_directory(ptr, ptr)\n"
            << "declare i32 @txrt_path_root_path(ptr, ptr)\n"
            << "declare i32 @txrt_path_stem(ptr, ptr)\n"
            << "declare i32 @txrt_path_compare(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_path_equivalent(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_system_initialize()\n"
            << "declare i32 @txrt_system_args(ptr)\n"
            << "declare i32 @txrt_system_current_directory(ptr)\n"
            << "declare i32 @txrt_system_set_current_directory(ptr)\n"
            << "declare i32 @txrt_system_executable_path(ptr)\n"
            << "declare i32 @txrt_system_temp_directory(ptr)\n"
            << "declare i32 @txrt_system_home_directory(ptr)\n"
            << "declare i32 @txrt_system_operating_system(ptr)\n"
            << "declare i32 @txrt_system_architecture(ptr)\n"
            << "declare i32 @txrt_system_cpu_count(ptr)\n"
            << "declare i32 @txrt_system_process_id(ptr)\n"
            << "declare i32 @txrt_system_has_capability(ptr, ptr)\n"
            << "declare i32 @txrt_env_contains(ptr, ptr)\n"
            << "declare i32 @txrt_env_get(ptr, ptr)\n"
            << "declare i32 @txrt_env_get_default(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_env_set(ptr, ptr)\n"
            << "declare i32 @txrt_env_remove(ptr, ptr)\n"
            << "declare i32 @txrt_env_snapshot(ptr)\n"
            << "declare i32 @txrt_io_write(ptr)\n"
            << "declare i32 @txrt_io_write_line(ptr)\n"
            << "declare i32 @txrt_io_write_error(ptr)\n"
            << "declare i32 @txrt_io_flush()\n"
            << "declare i32 @txrt_time_unix_millis(ptr)\n"
            << "declare i32 @txrt_time_monotonic_millis(ptr)\n"
            << "declare i32 @txrt_time_monotonic_micros(ptr)\n"
            << "declare i32 @txrt_time_sleep_millis(i64)\n\n";
    module_ << "declare i32 @txrt_time_duration_from_micros(i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_from_millis(i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_from_seconds(i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_add(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_sub(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_negate(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_as_micros(ptr, ptr)\n"
            << "declare i32 @txrt_time_duration_as_millis(ptr, ptr)\n"
            << "declare i32 @txrt_time_instant_now(ptr, ptr)\n"
            << "declare i32 @txrt_time_instant_elapsed(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_instant_after(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_sleep(ptr)\n"
            << "declare i32 @txrt_time_sleep_cancelled(ptr, ptr)\n\n";
    module_ << "declare i32 @txrt_time_parse_local_date(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_format_local_date(ptr, ptr)\n"
            << "declare i32 @txrt_time_date_add_days(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_date_add_months(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_date_days_between(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_parse_local_time(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_format_local_time(ptr, ptr)\n"
            << "declare i32 @txrt_time_parse_offset_datetime(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_offset_from_unix_millis(i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_time_format_offset_datetime(ptr, ptr)\n"
            << "declare i32 @txrt_time_datetime_difference(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_timezone_version(ptr)\n"
            << "declare i32 @txrt_time_at_zone(ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_resolve_local(ptr, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_format_zoned_datetime(ptr, ptr)\n"
            << "declare i32 @txrt_time_zoned_local_date(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_time_zoned_local_time(ptr, ptr, ptr)\n\n";
    module_ << "declare i32 @txrt_httpx_send(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_bytes(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_bytes(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post_bytes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http2(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_http2(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post_http2(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http2_bytes(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_http2_bytes(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post_http2_bytes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_http3(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post_http3(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3_bytes(ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_http3_bytes(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_post_http3_bytes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3_with_trust(ptr, ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3_with_trust_bytes(ptr, ptr, ptr, ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3_controlled(ptr, ptr, ptr, ptr, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http3_controlled_bytes(ptr, ptr, ptr, ptr, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_negotiated(ptr, ptr, ptr, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_negotiated_bytes(ptr, ptr, ptr, ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_stream(ptr, ptr, ptr, ptr, i64, ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_stream(ptr, ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_send_http2_stream(ptr, ptr, ptr, ptr, i64, ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_get_http2_stream(ptr, ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_open_session(ptr, i64, i1, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_open_secure_session(ptr, i64, i1, ptr, i1, ptr, ptr, i1, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_begin_request(ptr, ptr, ptr, ptr, i64, i64, i64, i1, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_write_request(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_finish_request(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_read_response_chunk(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_close_session(ptr)\n"
            << "declare i32 @txrt_httpx_close_request(ptr)\n"
            << "declare i32 @txrt_httpx_match_route(ptr, ptr, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_listen(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_listen_with_limit(ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_listen_h2c(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_listen_h2_tls(ptr, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_listen_h3(ptr, i64, ptr, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_accept(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_accept_bytes(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_accept_stream(ptr, ptr, i64, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_respond(ptr, ptr)\n"
            << "declare i32 @txrt_httpx_respond_bytes(ptr, ptr)\n"
            << "declare i32 @txrt_httpx_respond_stream(ptr, i64, ptr, ptr, ptr, i64)\n"
            << "declare i32 @txrt_httpx_serve_once(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_serve_once_bytes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_serve_routes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_serve_routes_bytes(ptr, ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_httpx_close_listener(ptr)\n"
            << "declare i32 @txrt_httpx_close_connection(ptr)\n"
            << "declare i32 @txrt_ws_connect(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_listen(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_listen_tls(ptr, i64, ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ws_accept(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_upgrade(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ws_send_text(ptr, ptr)\n"
            << "declare i32 @txrt_ws_send_binary(ptr, ptr)\n"
            << "declare i32 @txrt_ws_send_binary_stream(ptr, ptr, i64)\n"
            << "declare i32 @txrt_ws_receive(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_receive_binary(ptr, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_receive_binary_stream(ptr, ptr, i64, i64, ptr, ptr)\n"
            << "declare i32 @txrt_ws_get_close_status(ptr, ptr, ptr)\n"
            << "declare i32 @txrt_ws_ping(ptr, ptr)\n"
            << "declare i32 @txrt_ws_pong(ptr, ptr)\n"
            << "declare i32 @txrt_ws_close_with_reason(ptr, i64, ptr)\n"
            << "declare i32 @txrt_ws_reply_once(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_ws_reply_once_binary(ptr, ptr, i64, ptr)\n"
            << "declare i32 @txrt_ws_close_listener(ptr)\n"
            << "declare i32 @txrt_ws_close_connection(ptr)\n\n";
}

} // namespace tx
