# 平台实现保留原领域接口，由构建系统选源，避免向上层泄露系统句柄。
function(tx_replace_source target previous replacement)
    get_target_property(_sources ${target} SOURCES)
    list(REMOVE_ITEM _sources "${previous}")
    list(APPEND _sources "${replacement}")
    set_property(TARGET ${target} PROPERTY SOURCES "${_sources}")
endfunction()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    tx_replace_source(txc src/driver/child_process.cpp src/driver/child_process_linux.cpp)
    tx_replace_source(txstdlib src/stdlib/env.cpp src/stdlib/linux/env.cpp)
    get_target_property(_sources txstdlib SOURCES)
    list(REMOVE_ITEM _sources src/stdlib/env_snapshot.cpp)
    set_property(TARGET txstdlib PROPERTY SOURCES "${_sources}")
    tx_replace_source(txstdlib src/stdlib/system.cpp src/stdlib/linux/system.cpp)
    foreach(_file filesystem_extended file_stream_lock crypto_file_io file_atomic)
        tx_replace_source(txstdlib "src/stdlib/${_file}.cpp" "src/stdlib/linux/${_file}.cpp")
    endforeach()
    foreach(_file x509_parse x509_verify x509_pkcs12 process process_options
            process_spawn process_pipe process_run ipc_connection ipc_transport profile_sampler)
        tx_replace_source(txstdlib "src/stdlib/${_file}.cpp" "src/stdlib/${_file}_posix.cpp")
    endforeach()
    foreach(_file network_url dns httpx_client httpx_client_session httpx_client_tls ws_client filesystem_watch)
        tx_replace_source(txstdlib "src/stdlib/${_file}.cpp" "src/stdlib/${_file}_linux.cpp")
    endforeach()
    tx_replace_source(txstdlib src/backend/cpp/task_iocp.cpp src/backend/cpp/task_timer_posix.cpp)
    tx_replace_source(txstdlib src/backend/cpp/task_file_iocp.cpp src/backend/cpp/task_file_posix.cpp)
    get_target_property(_sources txstdlib SOURCES)
    list(REMOVE_ITEM _sources src/stdlib/httpx_winhttp.cpp src/stdlib/ws_client_stream.cpp)
    list(FILTER _sources EXCLUDE REGEX "src/stdlib/httpx_client_custom_tls.*[.]cpp$")
    list(APPEND _sources src/stdlib/httpx_curl.cpp)
    set_property(TARGET txstdlib PROPERTY SOURCES "${_sources}")
endif()
